In [3]:
!pip install pandas --upgrade

Requirement already satisfied: pandas in D:\dsml\dsml2\.myvenv\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in D:\dsml\dsml2\.myvenv\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in D:\dsml\dsml2\.myvenv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in D:\dsml\dsml2\.myvenv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in D:\dsml\dsml2\.myvenv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [14]:
import pandas as pd
import numpy as np

In [6]:
pd.__version__

'3.0.5'

## Datatype of pandas
1. DataFrame
2. Series

## Creating DataFrame

In [10]:
data = {
    "name": ["bob","charlie","aman"],
    "age": [25,30,35]
}
data

{'name': ['bob', 'charlie', 'aman'], 'age': [25, 30, 35]}

In [11]:
df  = pd.DataFrame(data)

In [13]:
df

      name  age
0      bob   25
1  charlie   30
2     aman   35

In [15]:
arr_data = np.array(
    [
        ["bob",25],
        ["charlie", 35],
        ["aman",26]
    ]
)

In [16]:
pd.DataFrame(arr_data, columns=["Name","age"])

      Name age
0      bob  25
1  charlie  35
2     aman  26

## Reading Data from files

In [21]:
titanic_df = pd.read_csv("titanic-data.csv", delimiter=",", header=0)

In [23]:
titanic_df.shape

(891, 12)

In [25]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [26]:
jason_data =pd.read_json("data.json")

In [27]:
type(jason_data)

pandas.DataFrame

## Accessing Data

In [32]:
name = titanic_df["Name"]
#name = titanic_df.Name

In [35]:
name_age = titanic_df[["Name","Age"]]
name_age

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [39]:
name_age.loc[:2,"Age"]

0    22.0
1    38.0
2    26.0
Name: Age, dtype: float64

In [41]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [42]:
titanic_df.shape

(891, 12)

In [44]:
titanic_df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [46]:
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [47]:
titanic_df.tail(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q